# Default values for quobyte-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

externaldns:
  name: external-dns
  image: registry.opensource.zalan.do/teapot/external-dns:latest
  enabled: true
  provider: google
  domainfilter: gce-test.quobyte.net 
  loglevel: debug
  annotation: quobyte.gce-test.quobyte.net.

quobyte:
  image: gcr.io/eda-eval/quobyte-server:3.0.pre4
  datadisks:
    - name: data0
      mountpoint: /var/lib/quobyte/devices/data0
    - name: data1
      mountpoint: /var/lib/quobyte/devices/data1
