# Default values for quobyte-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# You want to enable external-dns in case you want to use the cluster 
# volumes in GCE virtual machines.
# The client service or mount command need to be able to find the registries
# in this case by name since pods are ephemeral and change ip addresses.
externaldns:
  name: external-dns
  image: registry.opensource.zalan.do/teapot/external-dns:latest
  enabled: true
  provider: google
  domainfilter: gce-test.quobyte.net 
  loglevel: debug
  annotation: quobyte.gce-test.quobyte.net.

# Please make sure that data devices start with data in their basename
# On GKE data devices should be at least 840Gi to get the best iops performance.
# This is our default and minimum requirement
quobyte:
  image: gcr.io/eda-eval/quobyte-server:3.0.pre4
  maxopenfiles: 1048576
  maxprocs: 16384
  datadisks:
    - name: data0
      mountpoint: /var/lib/quobyte/devices/data0
    - name: data1
      mountpoint: /var/lib/quobyte/devices/data1
  s3:
    enabled: false
